INSERT INTO questions (question_id, question_text, difficulty_level_id, subject_id, image_id)
VALUES (DEFAULT,
        'If the charge on a capacitor is doubled, the value of its capacitance \(C\) will be',
        1,
        1,
        NULL),
		(DEFAULT,
        'The maximum electric field that a dielectric medium of a capacitor can withstand without breakdown (of its insulating property) is called its',
        1,
        1,
        NULL),
		(DEFAULT,
        'Consider a parallel plate capacitor of \(10\;\mu\)F (microfarad) with air filled in the gap between the plates. Now, exactly one-half of the space between the plates is filled with a dielectric of dielectric constant \(4\), as shown in the figure.The capacity of the capacitor changes to',
        1,
        1,
        1),
		(DEFAULT,
        'Two large metal plates are placed parallel to each other. The inner surfaces of plates are charged by \(+ \sigma\) and \(- \sigma\) \(C/m^2\). The electric field between the plates and outside the plates',
        1,
        1,
        2),
		(DEFAULT,
        'Two identical capacitors \(C_1\) and \(C_2\) (equal in value) are connected in series with a battery of \(e.m.f \; V_o\). They are fully charged. Now, a dielectric slab is inserted between the plates of \(C_2\). The potential diff. across \(C_1\) will',
        1,
        1,
        NULL);

INSERT INTO questions (question_id, question_text, difficulty_level_id, subject_id, image_id)
VALUES (DEFAULT,
        'A smooth parabolic wire track lies in the vertical plane \((x-y \; plane)\). The shape of track is defined by the equation \( y = x^2/a \) (where \(a\) is constant). A bead of mass \(m\) which can slide freely on the wire track, is placed at the position \(A(a, a)\). The track is rotated with constant angular speed \( \omega\) about \(y-axis\), such that there is no relative slipping between the ring and the track. Then \( \omega\) is equal to',
        2,
        1,
        NULL),
		(DEFAULT,
        'A uniform circular ring of mass per unit length \( \lambda\) and radius \(R\) is rotating with angular velocity \( \omega\) about its own axis in a gravity free space. Tension in the ring is',
        2,
        1,
        NULL),
		(DEFAULT,
        'A chain of mass per unit length \( \lambda\) and length \(1.5\; m\) rests on a fixed smooth sphere of radius \(R = (2/\pi)\; m\)  \; such that end \(A\) of chain is at the top of sphere while the other end is hanging freely as shown. The chain is held stationary by a horizontal thread \(PA\). The tension in this thread is',
        3,
        1,
        3),
		(DEFAULT,
        'An ideal gas with adiabatic exponent \( \gamma = 2\) goes through a cycle as shown in figure, in which absolute temperature varies \( \tau = 4\) times. Find efficiency of this cycle',
        2,
        1,
        4),
		(DEFAULT,
        'The potential energy of a \(4\;kg\) particle free to move along the \(x-axis\) is given by \(U(x)= \displaystyle  \frac {x^ {3}}{2} - \frac {5x^ {2}}{2}  +6x +3\). Total mechanical energy of the particle is \(17 J\). Then the maximum kinetic energy is',
        2,
        1,
        NULL),
		(DEFAULT,
        'If a mercury droplet of radius \(R\) and surface tension \(S\) is broken into 8 smaller droplets of equal size. Then the work done by the external agency is',
        1,
        1,
        NULL),
		(DEFAULT,
        'If \(n\) drops of a liquid, each with surface energy \(E\), join to form a single drop then',
        1,
        1,
        NULL),
		(DEFAULT,
        'A soap bubble of radius \(R\) is surrounded by another soap bubble of radius \(2R\), as shown. If surface tension = \(S\), then the pressure inside the smaller soap bubble, in excess of the atmospheric pressure, will be',
        1,
        1,
        5),
		(DEFAULT,
        'Two soap bubbles of radii \(R_1\) and \(R_2\) equal to \(4\; cm\) and \(5\;cm\) are touching each other over a common surface \(S_1S_2\) (shown in figure). Radius of the common surface will be',
        1,
        1,
        6),
		(DEFAULT,
        'Graph between the mass of liquid inside the capillary and the radius of capillary',
        1,
        1,
        NULL);

INSERT INTO questions (question_id, question_text, difficulty_level_id, subject_id, image_id)
VALUES (DEFAULT,
		'A particle of mass \(2\;kg\) moves in a straight line. If \(v\) is the velocity at a distance \(x\) from a fixed point on the line and \(v^2 = 3 - 4 x^2\) , then',
		1,
		1,
		NULL),
		(DEFAULT,
		'A particle moves along the \(z-axis\) according to the equation \(z=5+12\;cos\biggl(2\pi t + \displaystyle \frac{\pi}{2}\biggl)\), where \(z\) is in \(cm\) and \(t\) is in seconds. Select the correct alternative',
		1,
		1,
		NULL),
		(DEFAULT,
		'The amplitude of a particle in SHM is \(5\;cm\) and its time period is \(\pi\). At a displacement of \(3\;cm\) from its mean position the velocity in \(cm/sec\) will be',
		1,
		1,
		NULL),
		(DEFAULT,
		'At a particular position the velocity of a particle in SHM with amplitude \(A\) is \(\sqrt{3}/2\;\) of that at its mean position. In this position, its displacement is',
		1,
		1,
		NULL),
		(DEFAULT,
		'If the maximum velocity of a particle in SHM is \(v_o\), then its velocity at half the amplitude from position of rest will be',
		1,
		1,
		NULL),
		(DEFAULT,
		'The velocities of a particle executing S.H.M. are \(30\) cm/s and \(16\) cm/s when its displacements are \(8\) cm and \(15\) cm from the equilibrium position. Then its amplitude of oscillation in cm is',
		1,
		1,
		NULL),
		(DEFAULT,
		'The figure shows two coherent microwave sources \(S_1\) and \(S_2\) emitting waves of wavelength \(\lambda\) and separated by a distance \(3\lambda\) . The minimum non-zero value of \(y\) for point \(P\) to be an intensity maximum is (\(D>>\lambda\))',
		2,
		1,
		11),
		(DEFAULT,
		'A block of mass m is connected to three springs as shown in the figure. The block is displaced down slightly, from its mean position. The time period of oscillation is',
		2,
		1,
		12),
		(DEFAULT,
		'In the figure shown, a spring fixed to wall is initially undeformed. Now it is compressed by \(\sqrt{2}A\). Consider the collision of the block with the wall to be perfectly elastic. The time period of oscillation is',
		3,
		1,
		13),
		(DEFAULT,
		'Three identical rods of mass \(M\) and length \(L\)  are placed on one another on the table so as to produce the maximum overhang as shown in figure. The maximum possible overhang will be',
		2,
		1,
		14),
		(DEFAULT,
		'As shown in figure a small block of mass \(m = 1\; kg\) is placed over a wedge of mass \(M = 4\; kg\). All surfaces are smooth. Mass \(m\) is released from rest from top position of wedge. Find the velocity of block at the instant, it is leaving the wedge',
		2,
		1,
		15),
		(DEFAULT,
		'A solid sphere of mass \(2\;kg\) and radius \(1\;m\) is moving on a smooth ground with linear velocity \(v_o = 4\; m/s\) and angular velocity \(\omega_o=9 \;rad/s\) as shown in figure. It collides elastically with a rough wall of coefficient of friction \(\mu\) and after collision with the wall rolls without slipping in opposite direction. Find the coefficient of friction \(\mu\)',
		3,
		1,
		16),
		(DEFAULT,
		'The disc rolls without slipping on a smooth horizontal surface as shown. The speed of the centre \(C\) is \(v\). The speed of point \(A\) on the disc at the instant shown is',
		2,
		1,
		17),
		(DEFAULT,
		'A small sphere of mass \( 1 \) kg is rolling without slipping with linear speed \( v =\displaystyle \sqrt{\frac{200}{7}} \text{ m/s}.\) It leaves the inclined plane at point \( C \). Find the kinetic energy at the top just before leaving the inclined plane, neglecting any impact at \( B \) and assuming no slipping anywhere',
		2,
		1,
		18),
		(DEFAULT,
		'Initial angular velocity of the system shown is \(\omega_o\) and frame length is \(a\) . System is rotating about the vertical axle and frame has negligible mass compared to the four point masses each of mass \(m\). Due to an internal mechanism the spokes in the frame lengthen to \(2a\). Find new angular velocity of the system',
		2,
		1,
		19);
		
		












		